### ISSUE TITLE
How to use this?

### ISSUE THREAD

**Issue by lushangkan** [jd1378/v-scroll-threshold#28]
I added this plugin according to the readme, but it's only called once when the page is loaded, the scrolling doesn't respond, is it possible that it's because I'm using a scrollElement but the scrollElement doesn't load in the first time?

Code: 
```
<button type="button" title="add task" v-scroll-threshold="{ 
      threshold: 100,
      scrollElement: scrollEle,
      callback: callbackFunction
    }"
    class="addtaskbtn d-btn d-btn-circle border-none fixed w-14 h-14 bottom-8 right-8 bg-primary shadow justify-center items-center inline-flex z-30">

const scrollEle = ref<HTMLElement | undefined>();

const appStore = useAppStores();

onMounted(() => {
  const content: HTMLIonContentElement = (document.getElementsByTagName('ion-content')[0] as HTMLIonContentElement);
  content.getScrollElement().then((ele) => {
    scrollEle.value = ele;
  });

// omit the callback

});
```

**Comment by jd1378** [comment]
I think you are misusing this directive
this is not intended to be used with fixed elements
it's job is to detect if your scroll position is past your target element, which in a fixed element it never happens/doesn't make sense
for your case I suggest you edit and use the example I provided for you in the last issue you opened: https://codesandbox.io/s/pedantic-montalcini-tgxr84?file=/src/App.vue
